name: app_environment
channels:
  - snowflake
dependencies:
  - altair=5.0.1
  - matplotlib=3.7.2
  - pandas=2.0.3
  - plotly=5.9.0
  - python=3.8.*
  - snowflake-snowpark-python=
  - sqlparse=0.4.4
  - streamlit=1.26.0
